[build]
  command = "python -m pip install -r requirements.txt && rm -rf dist && mkdir -p dist/board-members && mkdocs build --clean --strict --site-dir dist/board-members && cp -R docs-home/. dist/"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.12"

